services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-url-shortener
    ports:
      - "8080:8080"
    container_name: go_url_shortener
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    #   db:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz || exit 1"]
    #   interval: 15s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 10s
      
  db: 
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ~/app/storage/pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: go-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres:
    external: true
    name: postgres